name: Build Docker Image and Save to Repo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t devdocs:latest .
          docker save devdocs:latest -o devdocs-docker.tar.gz

      - name: Deploy to built branch
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: built
          force_orphan: true
          user_name: 'UhaGroup'
          user_email: 'uha.company@gmail.com'
          commit_message: 'Build Docker image tar file'
